// State/render integration checks without a browser engine. This does not verify visual layout.
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {createStore} from '../dist/store.mjs';import {resonanceSentences,meaningPreview} from '../dist/resonance.mjs';
const data=JSON.parse(fs.readFileSync(new URL('../dist/poems.json',import.meta.url),'utf8'));
const elements=new Map();
class E{constructor(){this._html='';this.children=[];this.style={};this.isConnected=true;this.classList={add(){},remove(){},toggle(){},contains(){return false}}}set innerHTML(s){this._html=s;for(const id of [...elements.keys()])if(!['#app','#notice','#stars','#confirm','#confirm-title','#confirm-body'].includes(id))elements.delete(id)}get innerHTML(){return this._html}querySelector(k){return get(k)}querySelectorAll(){return []}addEventListener(){}setAttribute(){}removeAttribute(){}append(e){this.children.push(e)}focus(){}click(){}setPointerCapture(){}}
const get=k=>{if(!elements.has(k))elements.set(k,new E());return elements.get(k)};
class Memory{map=new Map();get length(){return this.map.size}key(i){return [...this.map.keys()][i]}getItem(k){return this.map.get(k)??null}setItem(k,v){this.map.set(k,v)}removeItem(k){this.map.delete(k)}}
let glyphGate=null;const soundCalls=[],delays=[];
// Controllers are tested independently by check-motion.mjs; here isolate application state.
const createWheel=(el,opts)=>({position:opts.initial,dragging:false,to(index){this.position=index;opts.onBegin();opts.onSettle(index)},destroy(){}});
const createEffects=()=>({clear(){},glyph:()=>glyphGate??Promise.resolve(),success(){},wrong(){},exit:()=>Promise.resolve(),enter(){}});
const createSound=()=>({unlock:async()=>true,click(){soundCalls.push('click')},tick(){soundCalls.push('tick')},success(){soundCalls.push('success')},stop(){soundCalls.push('stop')}});
const storage=new Memory();const registry=[];const context=vm.createContext({createMusic:()=>({sync(){},unlock(){},pause(){},resume(){}}),bootProgress(){},finishBoot:async()=>{},failBoot(){},createStore,createWheel,createEffects,createSound,resonanceSentences,meaningPreview,initStarCursor:()=>{},initButtonEffects:()=>{},SUCCESS_TIMING:{ready:1550,readDelay:260},console,document:{querySelector:get,querySelectorAll:()=>[],createElement:()=>new E(),body:new E(),addEventListener(){},modelContext:{registerTool(t){registry.push(t)}}},window:{scrollTo(){},addEventListener(){},scrollY:0},localStorage:storage,matchMedia:()=>({matches:false,addEventListener(){}}),location:{_hash:'',get hash(){return this._hash},set hash(v){this._hash=v.startsWith('#')?v:'#'+v},reload(){}},fetch:async()=>({ok:true,json:async()=>structuredClone(data)}),setTimeout:(fn,ms)=>{delays.push(ms);return delays.length},clearTimeout(){},queueMicrotask:f=>f(),getSelection:()=>({toString:()=>''}),URL,Blob,AbortController,Date,Map,Set,Array,Error,Promise});
const source=fs.readFileSync(new URL('../dist/app.mjs',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');vm.runInContext(source,context);await new Promise(r=>setImmediate(r));
const run=s=>vm.runInContext(s,context),html=()=>get('#app').innerHTML;
assert(html().includes('picker'));assert.equal(run('count()'),0);
assert(!soundCalls.includes('success'));assert(!html().includes('第 1 卷'));assert(html().includes('全集完成进度'));assert(!fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8').includes('data-action="journey"'));
const beforeSelect=delays.length;run('select(0,false)');assert.equal(delays.length,beforeSelect);assert.equal(run('current().phase'),'select');
assert.equal(run('validSession({id:"p001",mode:"journey",phase:"select",candidate:-1,skipped:[]}).mode'),'reading');
await run('select(0,false);checkAnswer()');assert.equal(run('current().phase'),'select');assert.equal(run('count()'),0);
await run('select(poem().options.indexOf(poem().answer),false);checkAnswer()');assert.equal(run('current().phase'),'read');assert.equal(run('count()'),1);assert(html().includes('海内存知己，'));assert(html().replace(/<[^>]+>/g,'').includes('天涯若比邻。'));assert(html().includes(data[0].realLife));
assert(html().includes('<h3>诗意今译'));assert(html().includes('<h3>此刻共鸣</h3><p class="resonance-tags">'+data[0].tags.join(' · ')+'</p><div class="resonance-copy"><p>'));assert(!html().includes('此刻的你'));assert.equal(soundCalls.filter(x=>x==='success').length,1);assert(html().includes('class="kaomoji"'));assert(html().includes(meaningPreview(data[0].meaning)));assert(!html().includes('已收入诗集'));assert(!html().includes('next-hint'));
const expand={dataset:{action:'meaning-toggle'},attrs:{},getAttribute(k){return this.attrs[k]},setAttribute(k,v){this.attrs[k]=v}};context.meaningEvent={target:{closest:()=>expand}};await run('action(meaningEvent)');assert.equal(get('#meaning-copy').textContent,data[0].meaning);assert.equal(expand.attrs['aria-expanded'],'true');await run('action(meaningEvent)');assert.equal(get('#meaning-copy').textContent,meaningPreview(data[0].meaning));assert.equal(expand.attrs['aria-expanded'],'false');
run('continueReading();current().phase="preview";renderHome()');assert(html().includes('已查看答案，尚未点亮'));assert.equal(run('count()'),1);
run('store.favorite("p002",true);view="library";tab="favorites";renderLibrary()');assert(html().includes('山中'));assert.equal(run('count()'),1);
run('tab="all";query="王安石";dynasty="宋";renderLibrary()');assert(run('filtered().every(p=>p.author==="王安石"&&p.dynasty==="宋")'));assert(run('filtered().length')>0);
const boat=data.find(p=>p.title==='泊船瓜洲');run(`practice=fresh('${boat.id}','practice');practice.phase='read';renderHome()`);assert(html().replace(/<[^>]+>/g,'').includes('明月何时照我还。'));assert.equal(run('active.id'),'p002');
run('practice=null;continueReading()');for(let i=0;i<10;i++)await run('next(true)');assert.equal(run('active.id'),'p012');assert.equal(run('active.phase'),'select');assert.equal(run('count()'),1);
for(let i=0;i<289;i++)await run('next(true)');assert.equal(run('active.phase'),'end');assert(html().includes('还有 299 首待点亮'));run('navigate("journey")');assert.equal(run('view'),'home');assert(!html().includes('诗词旅程'));
assert.deepEqual(registry.map(x=>x.name),['read_poetry_progress','open_poem_detail']);assert.equal(registry[0].execute({}).total,300);registry[1].execute({poemId:'p001'});assert(html().includes(data[0].title));assert.throws(()=>registry[1].execute({poemId:'bad'}));
assert(html().includes('<h3>此刻共鸣</h3><p class="resonance-tags">'+data[0].tags.join(' · ')+'</p><div class="resonance-copy"><p>'));assert(!html().includes('class="tags"'));
let release;glyphGate=new Promise(r=>release=r);run('continueReading();select(poem().options.indexOf(poem().answer),false)');const pending=run('checkAnswer()');assert.equal(run('count()'),2);
await run('action({target:{closest:()=>({dataset:{action:"answer"}})}})');assert.equal(run('current().phase'),'read');
run('navigate("settings")');release();await pending;assert.equal(run('view'),'settings');assert(!html().includes('full-quote'));assert.equal(run('transitioning'),false);
console.log('PASS: 应用渲染、完整联句、字段与共鸣首行、预览无奖励、收藏/筛选/跨旧卷连续阅读/全集跳过/旅程路由移除/旧会话兼容/滑动不自动判题、成功中断无旧页回写、动画期误点保护、WebMCP（模拟上下文）');
